[package]
name = "mygpio"
version = "0.1.0"
authors = ["Eddie.christian <eddiechristian@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
libc = "0.2.50"
lazy_static = "1.3.0"
ctrlc = "3.1.9"